cmd_drivers/misc/mediatek/fmradio/dummy.o := ccache /home/aarch64-linux-android-4.9-kernel/bin/aarch64-linux-android-gcc -Wp,-MD,drivers/misc/mediatek/fmradio/.dummy.o.d  -nostdinc -isystem /home/aarch64-linux-android-4.9-kernel/bin/../lib/gcc/aarch64-linux-android/4.9.4/include -I/home/android_kernel_xiaomi_hermes/arch/arm64/include -Iarch/arm64/include/generated  -I/home/android_kernel_xiaomi_hermes/include -Iinclude -I/home/android_kernel_xiaomi_hermes/arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I/home/android_kernel_xiaomi_hermes/include/uapi -Iinclude/generated/uapi -include /home/android_kernel_xiaomi_hermes/include/linux/kconfig.h  -I/home/android_kernel_xiaomi_hermes/drivers/misc/mediatek/fmradio -Idrivers/misc/mediatek/fmradio -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Werror=format -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -std=gnu89 -O2 -mgeneral-regs-only -fno-pic -Werror=frame-larger-than=1 -Wframe-larger-than=1400 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO   -I/home/android_kernel_xiaomi_hermes/drivers/misc/mediatek/mach/mt6795/include -D MTK_WCN_REMOVE_KERNEL_MODULE   -I/home/android_kernel_xiaomi_hermes/drivers/misc/mediatek/mach/mt6795/include -DWMT_PLAT_ALPS=1 -DMT6630_FM  -I/home/android_kernel_xiaomi_hermes/drivers/misc/mediatek/fmradio/inc -Idrivers/misc/mediatek/fmradio/inc  -I/home/android_kernel_xiaomi_hermes/drivers/misc/mediatek/fmradio/mt6630/inc -Idrivers/misc/mediatek/fmradio/mt6630/inc  -I/home/android_kernel_xiaomi_hermes/drivers/misc/mediatek/fmradio/../connectivity/combo/common/include -Idrivers/misc/mediatek/fmradio/../connectivity/combo/common/include  -I/home/android_kernel_xiaomi_hermes/drivers/misc/mediatek/fmradio/../connectivity/combo/common/linux/include -Idrivers/misc/mediatek/fmradio/../connectivity/combo/common/linux/include  -I/home/android_kernel_xiaomi_hermes/drivers/misc/mediatek/fmradio/../connectivity/common_detect -Idrivers/misc/mediatek/fmradio/../connectivity/common_detect    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(dummy)"  -D"KBUILD_MODNAME=KBUILD_STR(dummy)" -c -o drivers/misc/mediatek/fmradio/dummy.o /home/android_kernel_xiaomi_hermes/drivers/misc/mediatek/fmradio/dummy.c

source_drivers/misc/mediatek/fmradio/dummy.o := /home/android_kernel_xiaomi_hermes/drivers/misc/mediatek/fmradio/dummy.c

deps_drivers/misc/mediatek/fmradio/dummy.o := \

drivers/misc/mediatek/fmradio/dummy.o: $(deps_drivers/misc/mediatek/fmradio/dummy.o)

$(deps_drivers/misc/mediatek/fmradio/dummy.o):
